### PR TITLE
Fix/201 assetmeta serialization

### LINKED ISSUE #201: fix AssetMeta serialization
> Describe the  problem

Querying generic asset registered assets rpc crashes node with panic

> Expected result

Querying the endpoint returns the results

> Steps to reproduce

Start build on `develop` query the RPC endpoint
```
curl -H "Content-Type: application/json" -d \
'{
  "id":"1", "jsonrpc":"2.0",
  "method": "genericAsset_registeredAssets",
  "params":[]
}'
```

> Error Details
```
Thread 'http.worker30' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', /Users/<path>/.cargo/git/checkouts/plug-blockchain-25dc95d3d20d1ef4/c778f7e/prml/generic-asset/rpc/src/lib.rs:30
```

> Other information

affects plug 3.0-rc* only

Seems caused by serde unable to serialize u128 out of the box

### PR DESCRIPTION
**Pull request by JasonTulp**
Closes #201

### CODE REVIEW

**Review by aliXsed — APPROVED** [review]
Good job!

File: prml/generic-asset/src/lib.rs [hunk 1]
```diff
@@ -911,13 +911,14 @@ impl<T: Config> Module<T> {
...
 
-	pub fn registered_assets() -> Vec<(T::AssetId, AssetInfo<T::Balance>)> {
+	pub fn registered_assets() -> Vec<(T::AssetId, AssetInfo)> {
 		AssetMeta::<T>::iter().collect()
 	}
 
 	/// Return true if the specified asset of `who` is considered dust (insignificant).
 	fn is_dust(asset_id: T::AssetId, who: &T::AccountId) -> bool {
 		let existential_deposit = AssetMeta::<T>::get(asset_id).existential_deposit();
+		let existential_deposit: T::Balance = existential_deposit.unique_saturated_into();
```
Comment (aliXsed) [inline prml/generic-asset/src/lib.rs]: Can you try mix this line with the previous one?

File: prml/generic-asset/src/tests.rs [hunk 2]
```diff
@@ -260,7 +260,7 @@ fn transfer_dust_balance_can_create_an_account() {
 			Origin::signed(ALICE),
 			STAKING_ASSET_ID,
 			BOB,
-			asset_info.existential_deposit() - 1
+			asset_info.existential_deposit() as u64 - 1
```
Comment (aliXsed) [inline prml/generic-asset/src/tests.rs]: as u64 is not necessary any more

File: prml/generic-asset/src/types.rs [hunk 3]
```diff
@@ -47,15 +44,12 @@ impl<Balance: AtLeast32BitUnsigned + Copy> AssetInfo<Balance> {
...
-where
-	Balance: Default + One,
-{
+impl Default for AssetInfo {
 	fn default() -> Self {
 		Self {
 			symbol: vec![],
 			decimal_places: 4,
-			existential_deposit: One::one(),
+			existential_deposit: 1u64,
```
Comment (aliXsed) [inline prml/generic-asset/src/types.rs]: Perhaps better to just say 1
